"""Generates the gold-layer star-schema DDL from a list of profiles.

The schema has two layers:

**Conformed dimensions** (shared across every disease)
    - ``dim_etl_snapshot``          time-variant load/version dimension
    - ``dim_patient_record``        per-source-row surrogate; carries age + gender
    - ``dim_age_bracket``           OLAP age hierarchy
    - ``dim_gender``                gender lookup
    - ``dim_dataset``               registry of every disease profile loaded

**Per-disease facts** (one table per profile)
    - ``fact_<profile_name>``       columns = profile.fact_columns() + label + FKs

The builder also emits indexes, the ``metadata_*`` repository tables, and a
per-disease view ``vw_<profile_name>_full`` that joins fact -> dim for analytics.
"""

from __future__ import annotations

from typing import Iterable

from disease_warehouse.core.profile import ColumnSpec, DatasetProfile


SQL_TYPE_BY_ATTR = {
    "numeric": "REAL",
    "binary": "INTEGER",
    "nominal": "TEXT",
    "ordinal": "TEXT",
    "identifier": "INTEGER",
}


PROLOGUE = """\
-- =====================================================================
--  Gold-layer star schema (generated by disease_warehouse engine)
--  Conformed dims + per-disease facts. One row in a fact = one source
--  record after cleaning. patient_record_id is a warehouse surrogate.
-- =====================================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
"""


CONFORMED_TABLES = """\
DROP VIEW IF EXISTS vw_disease_summary;
DROP TABLE IF EXISTS etl_audit_log;
DROP TABLE IF EXISTS metadata_lineage;
DROP TABLE IF EXISTS metadata_data_dictionary;
DROP TABLE IF EXISTS dim_patient_record;
DROP TABLE IF EXISTS dim_dataset;
DROP TABLE IF EXISTS dim_age_bracket;
DROP TABLE IF EXISTS dim_gender;
DROP TABLE IF EXISTS dim_etl_snapshot;

CREATE TABLE dim_etl_snapshot (
    snapshot_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_timestamp TEXT    NOT NULL,
    pipeline_version   TEXT    NOT NULL,
    load_type          TEXT    NOT NULL CHECK (load_type IN ('full_refresh','incremental')),
    source_system      TEXT    NOT NULL,
    notes              TEXT    NOT NULL
);

CREATE TABLE dim_dataset (
    dataset_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    dataset_name    TEXT    NOT NULL UNIQUE,
    display_name    TEXT    NOT NULL,
    domain          TEXT    NOT NULL,
    description     TEXT    NOT NULL,
    profile_path    TEXT    NOT NULL,
    source_path     TEXT    NOT NULL,
    fact_table      TEXT    NOT NULL,
    snapshot_id     INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE
);

CREATE TABLE dim_age_bracket (
    age_bracket TEXT PRIMARY KEY,
    sort_order  INTEGER NOT NULL,
    lower_age   REAL,
    upper_age   REAL
);

CREATE TABLE dim_gender (
    gender_id   INTEGER PRIMARY KEY,
    gender_code TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_patient_record (
    patient_record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id       INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE,
    dataset_id        INTEGER NOT NULL REFERENCES dim_dataset(dataset_id) ON DELETE CASCADE,
    source_record_num INTEGER NOT NULL CHECK (source_record_num > 0),
    age               REAL,
    gender_id         INTEGER REFERENCES dim_gender(gender_id),
    age_bracket       TEXT REFERENCES dim_age_bracket(age_bracket)
);

CREATE TABLE metadata_data_dictionary (
    dictionary_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id         INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE,
    dataset_name        TEXT NOT NULL,
    table_name          TEXT NOT NULL,
    column_name         TEXT NOT NULL,
    source_column       TEXT,
    declared_type       TEXT NOT NULL,
    inferred_type       TEXT NOT NULL,
    attribute_type      TEXT NOT NULL,
    role                TEXT,
    description         TEXT NOT NULL,
    dtype               TEXT NOT NULL,
    null_count          INTEGER NOT NULL,
    null_pct            REAL NOT NULL,
    distinct_count      INTEGER NOT NULL,
    sample_values       TEXT,
    numeric_stats_json  TEXT,
    categorical_stats_json TEXT
);

CREATE TABLE metadata_lineage (
    lineage_id             INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id            INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE,
    dataset_name           TEXT    NOT NULL,
    pipeline_stage         TEXT    NOT NULL CHECK (pipeline_stage IN ('raw','cleaned','warehouse')),
    source_object          TEXT    NOT NULL,
    target_object          TEXT    NOT NULL,
    row_count              INTEGER NOT NULL CHECK (row_count >= 0),
    positive_count         INTEGER,
    negative_count         INTEGER,
    missing_cells          INTEGER NOT NULL CHECK (missing_cells >= 0),
    duplicate_rows         INTEGER NOT NULL CHECK (duplicate_rows >= 0),
    transformation_summary TEXT    NOT NULL
);

CREATE TABLE etl_audit_log (
    audit_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id  INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE,
    dataset_name TEXT    NOT NULL,
    audit_name   TEXT    NOT NULL,
    metric_name  TEXT    NOT NULL,
    metric_value REAL,
    status       TEXT    NOT NULL CHECK (status IN ('PASS','INFO','WARN','FAIL')),
    details      TEXT    NOT NULL
);
"""


CONFORMED_INDEXES = """\
CREATE INDEX idx_patient_record_dataset ON dim_patient_record(dataset_id);
CREATE INDEX idx_patient_record_snapshot ON dim_patient_record(snapshot_id);
CREATE INDEX idx_patient_record_age_bracket ON dim_patient_record(age_bracket);
CREATE INDEX idx_patient_record_gender ON dim_patient_record(gender_id);
CREATE INDEX idx_metadata_dict_dataset ON metadata_data_dictionary(dataset_name);
CREATE INDEX idx_metadata_lineage_dataset ON metadata_lineage(dataset_name);
"""


def _column_ddl(spec: ColumnSpec) -> str:
    sql_type = SQL_TYPE_BY_ATTR.get(spec.type, "TEXT")
    return f"    {spec.fact_column} {sql_type}"


def _hierarchy_columns(profile: DatasetProfile) -> list[tuple[str, str]]:
    """Return (column_name, sql_type) for every hierarchy except age_bracket
    (which already lives on dim_patient_record)."""
    out = []
    for h in profile.hierarchies:
        if h.new_column == "age_bracket":
            continue
        out.append((h.new_column, "TEXT"))
    return out


def fact_table_ddl(profile: DatasetProfile) -> str:
    cols: list[str] = [
        f"    fact_id INTEGER PRIMARY KEY AUTOINCREMENT",
        f"    , patient_record_id INTEGER NOT NULL REFERENCES dim_patient_record(patient_record_id) ON DELETE CASCADE",
        f"    , snapshot_id INTEGER NOT NULL REFERENCES dim_etl_snapshot(snapshot_id) ON DELETE CASCADE",
        f"    , dataset_id INTEGER NOT NULL REFERENCES dim_dataset(dataset_id) ON DELETE CASCADE",
    ]
    for spec in profile.fact_columns():
        cols.append(f"    , {spec.fact_column} {SQL_TYPE_BY_ATTR.get(spec.type, 'TEXT')}")
    for name, sql_type in _hierarchy_columns(profile):
        cols.append(f"    , {name} {sql_type}")
    cols.append(f"    , label INTEGER")

    return (
        f"DROP TABLE IF EXISTS {profile.fact_table};\n"
        f"CREATE TABLE {profile.fact_table} (\n"
        + "\n".join(cols)
        + "\n);\n"
        + f"CREATE INDEX idx_{profile.name}_patient ON {profile.fact_table}(patient_record_id);\n"
        + f"CREATE INDEX idx_{profile.name}_label   ON {profile.fact_table}(label);\n"
    )


def fact_view_ddl(profile: DatasetProfile) -> str:
    cols = [
        "dpr.patient_record_id",
        "dpr.snapshot_id",
        "dpr.source_record_num",
        "dpr.age",
        "COALESCE(dg.gender_code, 'Unknown') AS gender",
        "dpr.age_bracket",
    ]
    for spec in profile.fact_columns():
        cols.append(f"f.{spec.fact_column}")
    for name, _ in _hierarchy_columns(profile):
        cols.append(f"f.{name}")
    cols.append(f"f.label AS {profile.name}_label")

    return (
        f"DROP VIEW IF EXISTS vw_{profile.name}_full;\n"
        f"CREATE VIEW vw_{profile.name}_full AS\n"
        f"SELECT\n    " + ",\n    ".join(cols) + "\n"
        f"FROM {profile.fact_table} f\n"
        f"JOIN dim_patient_record dpr ON dpr.patient_record_id = f.patient_record_id\n"
        f"LEFT JOIN dim_gender dg ON dg.gender_id = dpr.gender_id\n"
        f"JOIN dim_dataset dd ON dd.dataset_id = dpr.dataset_id AND dd.dataset_name = '{profile.name}';\n"
    )


def summary_view_ddl(profiles: Iterable[DatasetProfile]) -> str:
    unions = []
    for prof in profiles:
        unions.append(
            f"SELECT '{prof.name}' AS dataset, COUNT(*) AS total_records, "
            f"SUM(CASE WHEN label = 1 THEN 1 ELSE 0 END) AS positive_cases, "
            f"ROUND(100.0 * SUM(CASE WHEN label = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS positive_rate_pct "
            f"FROM {prof.fact_table}"
        )
    return (
        "DROP VIEW IF EXISTS vw_disease_summary;\n"
        "CREATE VIEW vw_disease_summary AS\n"
        + "\nUNION ALL\n".join(unions)
        + ";\n"
    )


def build_schema_sql(profiles: list[DatasetProfile]) -> str:
    chunks = [PROLOGUE, CONFORMED_TABLES]

    drop_fact_chunks = [f"DROP TABLE IF EXISTS {p.fact_table};" for p in profiles]
    chunks.append("\n".join(drop_fact_chunks) + "\n")

    chunks.append(CONFORMED_INDEXES)
    for prof in profiles:
        chunks.append(fact_table_ddl(prof))
    for prof in profiles:
        chunks.append(fact_view_ddl(prof))
    chunks.append(summary_view_ddl(profiles))
    return "\n".join(chunks)
