"""Bundle the project into a lean zip for upload to the Colab demo notebook.

What's INCLUDED:
  - disease_warehouse/                 (engine code + YAML profiles)
  - datasets/                          (raw CSVs the profiles reference)
  - requirements.txt
  - CLAUDE.md                          (project documentation)
  - .env.example                       (so the prof sees the env-var template)
  - disease_warehouse_colab.ipynb      (the notebook itself, for convenience)

What's EXCLUDED:
  - .env                               (your API key — never zip this)
  - disease_warehouse/outputs/         (regenerated by `build`; ~67 MB)
  - __pycache__/, *.pyc                (Python bytecode)
  - .llm_cache.json                    (cached Gemini responses)
  - .git/, .venv/, .ipynb_checkpoints/, presentation/eda/models/ scratch
"""

from __future__ import annotations

import fnmatch
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_ZIP = ROOT / "datamining_project.zip"

INCLUDE_TOP = [
    "disease_warehouse",
    "datasets",
    "requirements.txt",
    "CLAUDE.md",
    ".env.example",
    "disease_warehouse_colab.ipynb",
    "INSTRUCTIONS_FOR_PROFESSOR.md",
]

# Only these YAMLs are shipped to the prof. Any other *.yaml in profiles/
# (local scratch experiments, half-finished tests, etc.) is excluded so the
# Colab demo doesn't trip over a broken profile the prof never asked for.
CANONICAL_PROFILES = {
    "cardio.yaml",
    "cdc_diabetes.yaml",
    "cdc_heart_disease.yaml",
    "chronic_kidney_disease.yaml",
    "diabetes.yaml",
    "heart_disease.yaml",
    "stroke.yaml",
}

EXCLUDE_DIR_NAMES = {
    "__pycache__",
    ".ipynb_checkpoints",
    "outputs",            # disease_warehouse/outputs/ — regenerated by build
    ".git",
    ".venv",
    "venv",
    "node_modules",
}

EXCLUDE_FILE_PATTERNS = [
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".env",
    ".env.local",
    ".llm_cache.json",
    "*.db-journal",
    "Thumbs.db",
    ".DS_Store",
]


def is_excluded_file(name: str) -> bool:
    return any(fnmatch.fnmatch(name, pat) for pat in EXCLUDE_FILE_PATTERNS)


def walk_included(start: Path):
    if start.is_file():
        if not is_excluded_file(start.name):
            yield start
        return
    for path in start.rglob("*"):
        # Skip excluded directories anywhere in the hierarchy.
        rel_parts = path.relative_to(start).parts
        if any(part in EXCLUDE_DIR_NAMES for part in rel_parts):
            continue
        if not path.is_file():
            continue
        if is_excluded_file(path.name):
            continue
        # Profile whitelist: only canonical YAMLs inside profiles/ ship.
        if (
            len(rel_parts) >= 2
            and rel_parts[-2] == "profiles"
            and path.suffix == ".yaml"
            and path.name not in CANONICAL_PROFILES
        ):
            continue
        yield path


def main() -> None:
    if not (ROOT / "disease_warehouse_colab.ipynb").exists():
        raise SystemExit(
            "[error] disease_warehouse_colab.ipynb missing — run "
            "scripts/build_colab_notebook.py first."
        )

    file_count = 0
    total_bytes = 0

    with zipfile.ZipFile(OUT_ZIP, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for top in INCLUDE_TOP:
            src = ROOT / top
            if not src.exists():
                print(f"  [skip] {top} (not present)")
                continue
            for path in walk_included(src):
                arcname = path.relative_to(ROOT).as_posix()
                zf.write(path, arcname)
                file_count += 1
                total_bytes += path.stat().st_size

    print()
    print(f"  wrote {OUT_ZIP}")
    print(f"  files            : {file_count:,}")
    print(f"  uncompressed     : {total_bytes / 1024 / 1024:,.1f} MB")
    print(f"  compressed       : {OUT_ZIP.stat().st_size / 1024 / 1024:,.1f} MB")


if __name__ == "__main__":
    main()
